# Generated by Django 2.1.5 on 2019-02-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status_id',
            field=models.SmallIntegerField(choices=[('1', 'проведена'), ('2', 'отложена'), ('3', 'сторно')], default=1, max_length=3),
        ),
    ]
