# Generated by Django 2.1.5 on 2019-02-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_auto_20190208_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
