# Generated by Django 2.1.5 on 2019-02-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_auto_20190211_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funds.ClientCategory'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funds.ClientType'),
        ),
    ]
