# Generated by Django 2.1.5 on 2019-02-11 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_auto_20190211_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.ClientType'),
        ),
    ]
