# Generated by Django 2.1.5 on 2019-02-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_auto_20190211_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=5, null=True)),
                ('ISO_digit', models.CharField(max_length=3)),
                ('ISO_char', models.CharField(max_length=3)),
            ],
        ),
    ]
