# Generated by Django 2.1.5 on 2019-02-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='short_name',
        ),
        migrations.AddField(
            model_name='country',
            name='ISO_short_char',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
