# Generated by Django 2.1.5 on 2019-02-12 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_auto_20190212_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.Country'),
        ),
    ]
