# Generated by Django 2.1.5 on 2019-02-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_country_latin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTypeLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.ClientType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clienttypelocale',
            unique_together={('locale', 'client_type')},
        ),
    ]
