# Generated by Django 2.1.5 on 2019-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_auto_20190214_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttypelocale',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
