# Generated by Django 2.1.5 on 2019-02-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0014_auto_20190215_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status_id',
        ),
    ]
