# Generated by Django 2.1.5 on 2019-02-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0015_remove_client_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status_id',
            field=models.SmallIntegerField(default='1'),
        ),
    ]
