# Generated by Django 2.1.5 on 2019-02-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0016_client_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategoryLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('client_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.ClientCategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clientcategorylocale',
            unique_together={('locale', 'client_category')},
        ),
    ]
