# Generated by Django 2.1.5 on 2019-02-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0017_auto_20190218_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='usersinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UsersInfo',
        ),
    ]
