# Generated by Django 2.1.5 on 2019-02-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0018_auto_20190221_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategoryLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('inner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.AccountCategory')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypeLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.AccountType')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.BalanceAccount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.Bank'),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.AccountCategory'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_client', to='funds.Client'),
        ),
        migrations.AlterField(
            model_name='account',
            name='saldo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.AccountSaldoType'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status_id',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='sync_partition_flag',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.AccountType'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttypelocale',
            unique_together={('locale', 'account_type')},
        ),
        migrations.AlterUniqueTogether(
            name='accountcategorylocale',
            unique_together={('locale', 'account_category')},
        ),
    ]
