# Generated by Django 2.1.4 on 2019-01-12 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inner_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inner_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPartitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=300)),
                ('balance_account', models.IntegerField()),
                ('index', models.SmallIntegerField()),
                ('category', models.SmallIntegerField(blank=True, null=True)),
                ('assignment', models.CharField(blank=True, max_length=300, null=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sync_partition_flag', models.BooleanField(blank=True, null=True)),
                ('status_id', models.SmallIntegerField()),
                ('user', models.IntegerField()),
                ('handle_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountSaldoTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inner_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_number', models.CharField(max_length=4, unique=True)),
                ('assignment', models.CharField(blank=True, db_column='Assignment', max_length=500, null=True)),
                ('inner_assignment', models.CharField(blank=True, db_column='InnerAssignment', max_length=200, null=True)),
                ('saldo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.AccountSaldoTypes')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.AccountTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Bankimport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField()),
                ('file_date', models.DateField()),
                ('file_name', models.CharField(max_length=255)),
                ('is_reverse', models.BooleanField(null=True)),
                ('db_cr_id', models.BooleanField(null=True)),
                ('db_bank_text_id', models.CharField(blank=True, max_length=200, null=True)),
                ('db_bank_name', models.CharField(blank=True, max_length=300, null=True)),
                ('db_account_number', models.CharField(blank=True, max_length=300, null=True)),
                ('db_client_text_id', models.CharField(blank=True, max_length=300, null=True)),
                ('db_client_name', models.CharField(blank=True, max_length=500, null=True)),
                ('cr_bank_text_id', models.CharField(blank=True, max_length=200, null=True)),
                ('cr_bank_name', models.CharField(blank=True, max_length=300, null=True)),
                ('cr_account_number', models.CharField(blank=True, max_length=300, null=True)),
                ('cr_client_text_id', models.CharField(blank=True, max_length=300, null=True)),
                ('cr_client_name', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('add_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.IntegerField(null=True)),
                ('currency_text_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_date', models.DateField(blank=True, null=True)),
                ('payment_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('add_info', models.CharField(blank=True, max_length=200, null=True)),
                ('status_id', models.SmallIntegerField()),
                ('user', models.IntegerField()),
                ('handle_time', models.DateTimeField(db_column='HandleTime')),
            ],
        ),
        migrations.CreateModel(
            name='BankImportPatterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_format_id', models.SmallIntegerField()),
                ('map', models.CharField(max_length=1000)),
                ('skip_first_rows', models.IntegerField(null=True)),
                ('skip_first_cols', models.IntegerField(null=True)),
                ('delimiter', models.CharField(blank=True, max_length=1, null=True)),
                ('quote', models.CharField(blank=True, max_length=1, null=True)),
                ('file_extentions', models.CharField(max_length=100)),
                ('after_sql', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_resident', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('encoding_id', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_id', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('country', models.SmallIntegerField(null=True)),
                ('contact_data', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.IntegerField()),
                ('handletime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('text_id', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.SmallIntegerField()),
                ('category', models.SmallIntegerField(null=True)),
                ('is_resident', models.BooleanField(default=True)),
                ('document', models.SmallIntegerField(null=True)),
                ('document_data', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_data', models.CharField(blank=True, max_length=300, null=True)),
                ('add_info', models.CharField(blank=True, max_length=300, null=True)),
                ('status_id', models.BooleanField()),
                ('user', models.IntegerField()),
                ('handletime', models.DateTimeField()),
                ('attracted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attracted_by_client', to='pymain.Clients')),
                ('responsible_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_responsible_client', to='pymain.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='Partitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.IntegerField()),
                ('handletime', models.DateTimeField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pymain.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.IntegerField()),
                ('order_id', models.SmallIntegerField()),
                ('currency', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_e', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status_id', models.SmallIntegerField()),
                ('user', models.IntegerField()),
                ('handletime', models.DateTimeField()),
                ('cr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_account', to='pymain.Accounts')),
                ('cr_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_client', to='pymain.Clients')),
                ('db_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_account', to='pymain.Accounts')),
                ('db_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_client', to='pymain.Clients')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Partitions')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPatterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.SmallIntegerField()),
                ('category', models.SmallIntegerField()),
                ('order_id', models.IntegerField()),
                ('icon_id', models.IntegerField(null=True)),
                ('level_id', models.SmallIntegerField()),
                ('form_width', models.IntegerField(null=True)),
                ('form_height', models.IntegerField(null=True)),
                ('after_sql', models.CharField(blank=True, max_length=1000, null=True)),
                ('status_id', models.SmallIntegerField()),
                ('user', models.IntegerField()),
                ('handletime', models.DateTimeField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pymain.TransactionPatterns')),
            ],
        ),
        migrations.AddField(
            model_name='bankimport',
            name='bank_import_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.BankImportPatterns'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='cr_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankimport_cr_account', to='pymain.Accounts'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='cr_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankimport_cr_bank', to='pymain.Banks'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='cr_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankimport_cr_client', to='pymain.Clients'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='db_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankimport_db_account', to='pymain.Accounts'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='db_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankimport_db_bank', to='pymain.Banks'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='db_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankimport_db_client', to='pymain.Clients'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='linked_transaction_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pymain.TransactionDetails'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Partitions'),
        ),
        migrations.AddField(
            model_name='bankimport',
            name='transaction_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.TransactionPatterns'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Banks'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Clients'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='parent_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_client', to='pymain.Clients'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='saldo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.AccountSaldoTypes'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.AccountTypes'),
        ),
        migrations.AddField(
            model_name='accountpartitions',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Accounts'),
        ),
        migrations.AddField(
            model_name='accountpartitions',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Partitions'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiondetails',
            unique_together={('transaction', 'order_id')},
        ),
        migrations.AlterUniqueTogether(
            name='accounts',
            unique_together={('number', 'client', 'balance_account', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='accountpartitions',
            unique_together={('account', 'partition')},
        ),
    ]
