# Generated by Django 2.1.4 on 2019-01-13 01:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('pymain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('inner_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientpartitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPatternsFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type_id', models.BooleanField()),
                ('tax_order_id', models.SmallIntegerField(null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read_only', models.BooleanField(null=True)),
                ('control_id', models.SmallIntegerField()),
                ('width', models.SmallIntegerField()),
                ('defaultvalue', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_required', models.BooleanField(null=True)),
                ('font_style', models.SmallIntegerField(null=True)),
                ('font_color', models.CharField(max_length=50, null=True)),
                ('dictionary_sql', models.CharField(blank=True, max_length=1000, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('left', models.SmallIntegerField()),
                ('transaction_pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.TransactionPatterns')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPatternsScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.SmallIntegerField(null=True)),
                ('db_account_index', models.SmallIntegerField(null=True)),
                ('cr_account_index', models.SmallIntegerField(null=True)),
                ('amount_sql', models.CharField(max_length=1000)),
                ('currency', models.IntegerField(null=True)),
                ('user', models.IntegerField()),
                ('handle_time', models.DateTimeField()),
                ('cr_account_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_cr_account_category', to='pymain.AccountCategories')),
                ('cr_account_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_cr_account_field', to='pymain.TransactionPatternsFields')),
                ('cr_account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_cr_account_type', to='pymain.AccountTypes')),
                ('cr_balance_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_cr_balance_account', to='pymain.BalanceAccounts')),
                ('cr_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_cr_client', to='pymain.Clients')),
                ('cr_client_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_cr_client_field', to='pymain.TransactionPatternsFields')),
                ('currency_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pymain.TransactionPatternsFields')),
                ('db_account_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_db_account_category', to='pymain.AccountCategories')),
                ('db_account_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_db_account_field', to='pymain.TransactionPatternsFields')),
                ('db_account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_db_account_type', to='pymain.AccountTypes')),
                ('db_balance_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_db_balance_account', to='pymain.BalanceAccounts')),
                ('db_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_db_client', to='pymain.Clients')),
                ('db_client_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_patterns_scheme_db_client_field', to='pymain.TransactionPatternsFields')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_date', models.DateField()),
                ('currency_rate', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('exchange_income', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_e', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('exchange_amount_e', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('currency', models.IntegerField()),
                ('exchange_currency', models.IntegerField(null=True)),
                ('payment_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('addinfo', models.CharField(blank=True, max_length=200, null=True)),
                ('status_id', models.SmallIntegerField()),
                ('user', models.IntegerField()),
                ('handle_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTaxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.SmallIntegerField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=15, null=True)),
                ('rate_method', models.SmallIntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_e', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status_id', models.SmallIntegerField(null=True)),
                ('user', models.IntegerField()),
                ('handle_time', models.DateTimeField()),
                ('cr_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_taxes_cr_client', to='pymain.Clients')),
                ('db_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_taxes_db_client', to='pymain.Clients')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Transactions')),
            ],
        ),
        migrations.CreateModel(
            name='UserPartitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.SmallIntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pymain.Clients')),
            ],
        ),
        migrations.AlterField(
            model_name='bankimport',
            name='handle_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partitions',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pymain.Clients'),
        ),
        migrations.AddField(
            model_name='userpartitions',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Partitions'),
        ),
        migrations.AddField(
            model_name='userpartitions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Users'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='bankimport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pymain.Bankimport'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='cr_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_cr_account', to='pymain.Accounts'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='cr_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_cr_client', to='pymain.Clients'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='db_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_db_account', to='pymain.Accounts'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='db_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_db_client', to='pymain.Clients'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pymain.Transactions'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Partitions'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.TransactionPatterns'),
        ),
        migrations.AddField(
            model_name='transactionpatternsscheme',
            name='partition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pymain.Partitions'),
        ),
        migrations.AddField(
            model_name='transactionpatternsscheme',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.TransactionPatterns'),
        ),
        migrations.AddField(
            model_name='clientpartitions',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymain.Partitions'),
        ),
        migrations.AlterUniqueTogether(
            name='userpartitions',
            unique_together={('user', 'partition')},
        ),
        migrations.AlterUniqueTogether(
            name='transactiontaxes',
            unique_together={('transaction', 'order_id')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionpatternsscheme',
            unique_together={('pattern', 'order_id')},
        ),
        migrations.AlterUniqueTogether(
            name='clientpartitions',
            unique_together={('client', 'partition')},
        ),
    ]
