# Generated by Django 2.1.4 on 2019-01-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pymain', '0002_auto_20190113_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=5, null=True)),
                ('ISO_digit', models.CharField(max_length=3)),
                ('ISO_char', models.CharField(max_length=3)),
                ('status_id', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bankimport',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pymain.Currency'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='cr_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cr_account', to='pymain.Accounts'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='cr_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cr_client', to='pymain.Clients'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Currency'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='db_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='db_account', to='pymain.Accounts'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='db_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='db_client', to='pymain.Clients'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Partitions'),
        ),
        migrations.AlterField(
            model_name='transactionpatternsscheme',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pymain.Currency'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_currency', to='pymain.Currency'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exchange_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_exchange_currency', to='pymain.Currency'),
        ),
    ]
