# Generated by Django 2.1.4 on 2019-01-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymain', '0003_auto_20190113_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='bria_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
