# Generated by Django 2.1.4 on 2019-01-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pymain', '0004_usersinfo_bria_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pymain.Users'),
            preserve_default=False,
        ),
    ]
