# Generated by Django 2.1.4 on 2019-01-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pymain', '0005_usersinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontaxes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
    ]
