# Generated by Django 2.1.4 on 2019-01-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pymain', '0008_auto_20190115_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='handletime',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='handletime',
        ),
        migrations.RemoveField(
            model_name='partitions',
            name='handletime',
        ),
        migrations.RemoveField(
            model_name='transactiondetails',
            name='handletime',
        ),
        migrations.RemoveField(
            model_name='transactionpatterns',
            name='handletime',
        ),
        migrations.AddField(
            model_name='banks',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partitions',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transactionpatterns',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='bankimport',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankimport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='partitions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='transactionpatterns',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='transactionpatternsscheme',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactionpatternsscheme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='handle_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pymain.Users'),
        ),
    ]
