# Generated by Django 2.1.5 on 2019-02-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0019_auto_20190221_1709'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
