# Generated by Django 2.1.5 on 2019-01-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='bankimport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Bankimport'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='cr_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_cr_account', to='transactions.Accounts'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='db_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_db_account', to='transactions.Accounts'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exchange_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exchange_amount_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exchange_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_exchange_currency', to='transactions.Currency'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='exchange_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Transactions'),
        ),
    ]
