# Generated by Django 2.1.5 on 2019-01-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190125_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.TransactionPatterns'),
        ),
    ]
