# Generated by Django 2.1.4 on 2018-12-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_classes',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('inner_name', models.CharField(blank=True, db_column='InnerName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'AccountClasses',
                'managed': False,
            },
        ),
    ]
