name = input('Як тебе звати? ')
city = input('З якого ти міста? ')
school = input('Номер твоєї школи? ')
class_ = input('В якому класі ти навчаєшся? ')

print()
print()
print()
print('Грамота')
print()
print('нагороджуеться ' + name + ',')
print('ученик(-ця) ' + class_ + ' класу,')
print("школи № " + school + ', міста '+ city)
print('за 1 місце у конкурсі з математики "Кенгуру" ')
